export const pixieData = [
  {
    emotionTags: ["beautiful"],
    isGif: false,
    image: "beautiful.png",
    alt: "Pixie looking at leafs falling down from a tree",
  },
  {
    emotionTags: ["beautiful", "cute"],
    isGif: false,
    image: "beautiful1.png",
    alt: "Pixie sitting in tall grass and looking at clouds",
  },
  {
    emotionTags: ["chill", "cute"],
    isGif: false,
    image: "chill.jpeg",
    alt: "Pixie laying down under an umbrella at the beach",
  },
  {
    emotionTags: ["cold", "cute"],
    isGif: false,
    image: "cold.jpeg",
    alt: "Pixie covered with warm scarfs",
  },
  {
    emotionTags: ["confused"],
    isGif: false,
    image: "confused.jpeg",
    alt: "Pixie laying down on a couch wondering whats happening",
  },
  {
    emotionTags: ["confused"],
    isGif: false,
    image: "confused1.jpeg",
    alt: "Pixie looking confused",
  },
  {
    emotionTags: ["cute"],
    isGif: false,
    image: "cute.png",
    alt: "Pixie's tongue is out,looking cute",
  },
  {
    emotionTags: ["cute"],
    isGif: false,
    image: "cute1.jpeg",
    alt: "Pixie looking at the camera with her tongue out and looking cute",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry.gif",
    alt: "Pixie is eating and apple",
  },
  {
    emotionTags: ["impatient"],
    isGif: false,
    image: "impatient.jpeg",
    alt: "Pixie sitting on a chair impatiently waiting to go home",
  },
  {
    emotionTags: ["relaxed"],
    isGif: false,
    image: "peaceful.jpeg",
    alt: "Pixie looking relaxed while getting scratched",
  },
  {
    emotionTags: ["proud"],
    isGif: false,
    image: "proud.jpeg",
    alt: "Pixie wearing a NY bandana and looking proud",
  },
  {
    emotionTags: ["scary"],
    isGif: false,
    image: "scary.jpeg",
    alt: "Pixie is watching you while you sleep and her eyes are glowing",
  },
  {
    emotionTags: ["scary", "relaxed"],
    isGif: false,
    image: "scary1.png",
    alt: "Pixie laying down on her bed looking scary and relaxed",
  },
  {
    emotionTags: ["scary", "hungry"],
    isGif: true,
    image: "scary2.gif",
    alt: "Pixie attacking her rat toy and biting",
  },
  {
    emotionTags: ["scary"],
    isGif: false,
    image: "scary2.jpeg",
    alt: "Pixie showing her teeths",
  },
  {
    emotionTags: ["sleepy", "tired"],
    isGif: true,
    image: "sleepy.gif",
    alt: "Pixie sleeping on the couch with her mouth open",
  },
  {
    emotionTags: ["sleepy", "tired"],
    isGif: false,
    image: "sleepy.jpeg",
    alt: "Pixie sleeping at the beach",
  },
  {
    emotionTags: ["sleepy", "tired"],
    isGif: true,
    image: "tired.gif",
    alt: "Pixie trying to sleep at work",
  },
  {
    emotionTags: ["tired", "sleepy", "relaxed"],
    isGif: false,
    image: "tired.jpeg",
    alt: "Pixie laying down on her back, relaxed and sleeping",
  },
  {
    emotionTags: ["tired", "sleepy"],
    isGif: true,
    image: "tired1.gif",
    alt: "Pixie looking tired on the couch",
  },
  {
    emotionTags: ["tired", "sleepy"],
    isGif: false,
    image: "tired2.jpeg",
    alt: "Pixie sleeping with her mouth open",
  },
  {
    emotionTags: ["cute", "tired", "sleepy"],
    isGif: false,
    image: "tired3.jpeg",
    alt: "Pixie trying to sleep in the car while laying her head on my knee",
  },
  {
    emotionTags: ["beautiful"],
    isGif: false,
    image: "beautiful2.jpeg",
    alt: "Pixie posing in the forest",
  },
  {
    emotionTags: ["cute", "relaxed"],
    isGif: false,
    image: "cute2.jpeg",
    alt: "Pixie looking at the camera",
  },
  {
    emotionTags: ["relaxed"],
    isGif: false,
    image: "relaxed.jpeg",
    alt: "Pixie laying down on her back and taking a sun bath",
  },
  {
    emotionTags: ["relaxed", "cute"],
    isGif: false,
    image: "relaxed1.jpeg",
    alt: "Pixie smelling flowers",
  },
];
